### ISSUE TITLE
Photos upside down

### ISSUE THREAD

**Issue by Vandenberg5** [UGS-GIO/rockcore#15]
There are still photos that are upside down

for example: Main Canyon 23-7-15-23

**Comment by Vandenberg5** [comment]
the "top" in the core box should be in the upper left whenever possible.

**Comment by marshallrobinson** [comment]
I may be wrong, but I think I this is because the web application displays the currently-saved orientation of the photos. So, in order to fix this, the photos would have to be re-saved in the correct orientation using Photoshop or some other photo-editing software (Irfanview).

**Comment by PNatCoreCenter** [comment]
I have looked at the Main Canyon photographs on the web server and on the G drive.  The first image is the Main Canyon Directory on the web server.  ![web photographs](https://user-images.githubusercontent.com/70150347/91056884-bd085c00-e5e3-11ea-9078-9627adb22fba.JPG)
My computer shows all images are TOP on the upper left and BOTTOM on lower right.  I selected the files as a group and rotated them right twice (180 degrees or flipped upside down).  I excited the directory, reconnected and all the photographs were upside down.  I then selected all the photographs again and rotated them left 180 degrees which put the TOP back at the upper left.  I excited the directory and reconnect they appear with the TOP in the upper left corner.

The second image is the same directory on the G drive where we have the JPG and the RAW file images.  
![g drive web photograph](https://user-images.githubusercontent.com/70150347/91057544-8ed74c00-e5e4-11ea-8fec-8030ea2d2c0f.JPG)  The core photographs have the TOP in the upper right.  You can see that one photograph is displayed horizontally.  This is the original orientation of the photograph.  I have rotated these several times.

This happens randomly and frequently.  I think that the original photograph files have an IMAGE rotation value in the metadata and a secondary Rotation positive or negative number.  I think that different software platforms read the photographs orientation differently.  That is why my photograph orientation can be observed differently on  Mike V computer, the web server, Cheryl's computer, etc.

I think we need a common software platform that manages core photographs or images in general.  It will read the image orientation the same way each time and allow us to figure out how to upload the photographs so that they display correctly.

We have started, with this last batch of core photographs, here at the core center rotating the images to the correct orientation when they are saved to the RAW and JPG files on the computer.  I don't know if this will address the problem with picture orientation but they will start in the correct orientation from this point.

**Comment by PNatCoreCenter** [comment]
See issue #17 for core photograph comments

**Comment by Vandenberg5** [comment]
seems to be fixed now
